
steps:

- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/cowsay:latest'
  ]

- id: Build Singularity Image
  name: 'quay.io/singularity/singularity:v3.7.1'
  args: ['build',
         'cowsay.sif',
         'docker-daemon://gcr.io/${PROJECT_ID}/cowsay:latest']

- id: Fluid CI/CB
  name: 'gcr.io/research-computing-cloud/fluid-run:latest'
  args: 
  - '--build-id=${BUILD_ID}'
  - '--git-sha=${COMMIT_SHA}'
  - '--artifact-type=singularity'
  - '--singularity-image=cowsay.sif'
  - '--project=${PROJECT_ID}'
  - '--zone=${_ZONE}'
  - '--ci-file=fluid-run.yaml'
  - '--cluster-type=rcc-ephemeral'
  - '--rcc-tfvars=ci/fluid.auto.tfvars'

timeout: 1800s

substitutions:
  _ZONE: 'us-west1-b'
