
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/fluid-run:${TAG_NAME}',
  ]

images: ['gcr.io/${PROJECT_ID}/fluid-run:${TAG_NAME}']
