
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/fluid-run:${SHORT_SHA}',
         '-t',
         'gcr.io/${PROJECT_ID}/fluid-run:${_ARTIFACT_TAG}'
  ]

images: ['gcr.io/${PROJECT_ID}/fluid-run:${SHORT_SHA}',
         'gcr.io/${PROJECT_ID}/fluid-run:${_ARTIFACT_TAG}']

substitutions:
  _ARTIFACT_TAG: 'dev'
