
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/fluid-cicb:${SHORT_SHA}'
         '-t',
         'gcr.io/${PROJECT_ID}/fluid-cicb:latest'
  ]

images: ['gcr.io/${PROJECT_ID}/fluid-cicb:${SHORT_SHA}',
         'gcr.io/${PROJECT_ID}/fluid-cicb:latest']
